### ISSUE TITLE
assetsssetsllies.png error?

### ISSUE THREAD

**Issue by sick107** [KrisKamweru/bbs-auto-bot#7]
Hey, I'm not sure if this (great idea of a) project is dead, but incase anyone is still willing to help out, I've come across this 'error', well I'm not really sure what it is, but I would like to bypass this issue so that I may get this farmbot to run, its as if its asking me to add assets that don't exist in the farmbot or test file, and continues to do so even after I add an asset with the given name. 
I get this error after the bot clicks on the prepare for quest button, what should I do?

![Screenshot 2021-10-15 130623](https://user-images.githubusercontent.com/20930770/137526058-85205f99-413d-4235-b268-232b56880fda.png)

Hopefully someone can help me with this issue, that way anyone who comes across it, will know how to fix it :)

**Comment by sick107** [comment]
Update, looks like all I had to do was add updated/missing assets. Though, even after following all other instructions, such as the test python file, the bot still won't run anywhere except for clicking a new story quest and staying in the prep for quest screen. I even changed the image to png, as well as the jpg to png in the farmbot python file, but still no luck.

**Comment by KrisKamweru** [comment]
Seems to be an issue with it not finding what seems to be a typo? Not sure how the filepath assets\assetsllies.png popped up. Don't remember making one of those

Looking at line 185 should give a solid idea of what file is actually being looked for

Word of warning, some of the files are definitely out of date at this point. Would probably be easiest to just make new asset files
I also did see they changed how the ally selection screen works so that's broken anyways
